name: Linux Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: write
    steps:
      - name: Check system arch
        run: uname -m
