name: Windows Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022-arm

    permissions:
      contents: write
    steps:
      - name: Check system arch
        run: wmic os get osarchitecture
      
